### PR TITLE
do not install dependencies

### PR DESCRIPTION
**Pull request by kirillseva**
@robertzk @peterhurford

### CODE REVIEW

**Comment by peterhurford** [comment]
The plan is to instead include all the dependencies in the lockbox file?  ...or figure out how to get packages to have lockbox files?

**Comment by kirillseva** [comment]
@peterhurford yeah, for now you'd have to manually pull in all dependencies either in your main library or add them to your lockfile (which we do now anyway). This PR is kind of like a bugfix for when your lockbox tries to install stuff that it wasn't asked for

**Comment by robertzk** [comment]
This will have some unintended consequences, in particular with respect to a [fresh Syberia project](https://github.com/syberia/example.sy). I'm not comfortable merging this at the moment. A long-term solution is correct topological sorting of the whole dependency chain and then installing it explicitly.

**Comment by peterhurford** [comment]
Should be obsolete by https://github.com/robertzk/lockbox/pull/73

**Pull request closed without merging**
