### PR TITLE
Install suggests

### PR DESCRIPTION
**Pull request by davidboren**
Just creating a pr for commenting purposes (also here: https://github.com/robertzk/lockbox/pull/90)
We're timing out on the test now, indicating that we're installing more packages.  Either I whittle down the installations used in the test or we increase the timing limits for CI.

### CODE REVIEW

**Comment by robertzk** [comment]
@davidboren CI should be green here; triggering a rebuild.

**Comment by davidboren** [comment]
@robertzk we are getting a timeout on this latest commit, because we've introduced more installations.  Is there an easy way to increase CI's timeout, or should we cut down some dependencies in the test?

**Comment by robertzk** [comment]
@davidboren CI failure happened twice now -- think there's some infinite loop going on.

**Comment by davidboren** [comment]
@robertzk changed the test to show output now (can remove) and tested locally no problem:

``` r
> devtools::test("~/dev/lockbox")
Loading lockbox
Loading required package: testthat
Testing lockbox
pending: .
random-dependencies: Retrieving dependency info......................................
Installing dependency base64enc from CRAN
Installing dependency stringi from CRAN
Installing dependency magrittr from CRAN
Installing dependency mime from CRAN
Installing dependency formatR from CRAN
Installing dependency highr from CRAN
Installing dependency markdown from CRAN
Installing dependency stringr from CRAN
Installing dependency evaluate from CRAN
Installing dependency rstudioapi from CRAN
Installing dependency jsonlite from CRAN
Installing dependency git2r from CRAN
Installing dependency withr from CRAN
Installing dependency lazyeval from CRAN
Installing dependency R6 from CRAN
Installing dependency whisker from CRAN
Installing director 0.2.1 from github
Installing memoise 1.0.0 from CRAN
Installing objectdiff 0.2.3.9000 from github
Installing crayon 1.2.1 from CRAN
Installing dependency gmailr from github
Installing devtools 1.10.0.9000 from github
Installing syberiaStructure 0.2.2 from github
Installing foreign 0.8.66 from CRAN
Installing knitr 1.12.3 from CRAN
Installing stagerunner 0.5.2 from github
Installing mungebits 0.3.13 from github
Installing tundra 0.2.3 from github
Installing mungebits2 0.1.0 from github
Installing Rcpp 0.12.3 from CRAN
Installing dependency plyr from CRAN
Installing statsUtils 0.1.4 from github
Installing syberiaStages 0.2.3 from github
Installing lubridate 1.5.0 from CRAN
Successfully loaded lockbox.

DONE ===========================================================================
Warning message:
package ‘testthat’ was built under R version 3.2.5
```

I'm pretty sure we are just dealing with timeout, not infinite loop.  I used devtools for testing, though...  If we used devtools::test it might actually register the output and not timeout.  But honestly I'm not that familiar with Travis to know how and why we're doing it the way we're currently doing it and whether we would even want to switch...

**Comment by robertzk** [comment]
@davidboren Still not sure how to get around the timeout issue on CI. It should be printing installation output?

**Comment by davidboren** [comment]
If it uses devtools::test then I'm pretty sure it should be.  It does locally when using devtools::test.  Maybe theres some other sink in use?  I added a split = TRUE to the logfile sink, so it outputs to that logfile but also prints to console.  Does so in real time.  Watching it go right now.   How does the line from the yml file "./travis-tool.sh run_tests" actually run the tests?

**Pull request closed without merging**
