### PR TITLE
Install specific version from CRAN

### PR DESCRIPTION
**Pull request by kirillseva**
Try CRAN, if the version is not found - try CRAN archive

### CODE REVIEW

**Comment by kirillseva** [comment]
damn coveralls srsly?

**Comment by robertzk** [comment]
Nice!! Will verify when I'm back home and merge.

**Comment by kirillseva** [comment]
`options(lockbox.CRAN_mirror)` or Rstudio by default

**Comment by kirillseva** [comment]
When starting my private project:

``` r
Error in match(el, set, 0L) :
  could not find function "installed.packages"
Error in match(el, set, 0L) :
  Must have installed the package crayon::1.0.0
```

I think this pull-request would solve it. Would like it merged

**Comment by kirillseva** [comment]
Too bad I can't test it because I can't get lockbox to run lol

**Comment by robertzk** [comment]
Thanks! Moved to https://github.com/robertzk/lockbox/pull/15

**Pull request closed without merging**
